# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SAGAssign
                                 A QGIS plugin
 update the attriubutes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-10-28
        git sha              : $Format:%H$
        copyright            : (C) 2023 by SADA
        email                : mailtosada2020@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from pathlib import Path

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon, QKeySequence
from qgis.PyQt.QtWidgets import QAction, QWidget, QPushButton, QShortcut
# Initialize Qt resources from file resources.py
from .resources import *
from qgis.core import *
from qgis.gui import *
from qgis.utils import *
from PyQt5.QtCore import QSize

# Import the code for the DockWidget
from .SAG_assign_dockwidget import SAGAssignDockWidget
import os.path
import math


class SAGAssign:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SAGAssign_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&SAG Assign')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'SAGAssign')
        self.toolbar.setObjectName(u'SAGAssign')
        self.toolbar.setIconSize(QSize(32, 32))  # Force 32x32 icon size

        #print "** INITIALIZING SAGAssign"

        self.pluginIsActive = False
        self.dockwidget = None


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('SAGAssign', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    @staticmethod
    def plugin_path(*args) -> Path:
        """ Return the path to the plugin root folder or file. """
        path = Path(__file__).resolve().parent
        for item in args:
            path = path.joinpath(item)
        return path

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        # icon_path = ':/plugins/SAG_assign/icon.png'
        self.add_action(
            str(self.plugin_path('icon.png')),
            text=self.tr(u'SAG Assign'),
            callback=self.run,
            parent=self.iface.mainWindow())

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING CatAssign"

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        #print "** UNLOAD SAGAssign"

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&SAG Assign'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    def append_text(self, value):
        current = self.dockwidget.text_input_1.text()
        self.dockwidget.text_input_1.setText(current + value)

    def set_text(self, value):
        self.dockwidget.text_input_1.setText(value)

    def update_sag_attribute(self):
        try:
            value = self.dockwidget.text_input_1.text()
            layer = iface.activeLayer()
            if not layer:
                QgsMessageLog.logMessage("❌ No active layer found.")
                return
            if not layer.isEditable():
                QgsMessageLog.logMessage("❌ Layer is not editable.")
                return

            selected = layer.selectedFeatures()
            if not selected:
                QgsMessageLog.logMessage("❌ No features selected.")
                return

            index = layer.fields().indexFromName("SAG")
            if index == -1:
                QgsMessageLog.logMessage("❌ Field 'SAG' not found.")
                return

            for feat in selected:
                feat.setAttribute(index, value)
                layer.updateFeature(feat)
                QgsMessageLog.logMessage("✅ SAG updated to " + value)

        except Exception as e:
            QgsMessageLog.logMessage(f"❌ Error in update_sag_attribute: {str(e)}")
        finally:
            # Clear the textbox after update
            self.dockwidget.text_input_1.clear()

    #--------------------------------------------------------------------------

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            #print "** STARTING SAGAssign"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = SAGAssignDockWidget()

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            # TODO: fix to allow choice of dock location
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.setFloating(True)
            self.dockwidget.show()
        #Set Attribute Buttons
        self.dockwidget.btn_S0.clicked.connect(lambda: self.append_text("0"))
        self.dockwidget.btn_S1.clicked.connect(lambda: self.append_text("1"))
        self.dockwidget.btn_S2.clicked.connect(lambda: self.append_text("2"))
        self.dockwidget.btn_S3.clicked.connect(lambda: self.append_text("3"))
        self.dockwidget.btn_S4.clicked.connect(lambda: self.append_text("4"))
        self.dockwidget.btn_S5.clicked.connect(lambda: self.append_text("5"))
        self.dockwidget.btn_S6.clicked.connect(lambda: self.append_text("6"))
        self.dockwidget.btn_S7.clicked.connect(lambda: self.append_text("7"))
        self.dockwidget.btn_S8.clicked.connect(lambda: self.append_text("8"))
        self.dockwidget.btn_S9.clicked.connect(lambda: self.append_text("9"))
        self.dockwidget.btn_S10.clicked.connect(lambda: self.append_text("10"))

        # NULL button sets text box to 'N/A'
        self.dockwidget.btn_SnULL.clicked.connect(lambda: self.set_text("N/A"))

        # OK button writes text box value to "SAG"
        self.dockwidget.btn_SBOX.clicked.connect(self.update_sag_attribute)
        

    
    def Set_sample(self):
        layer = iface.activeLayer()
        if layer.isEditable():
            selected_features = layer.selectedFeatures()
            for feat  in selected_features:
                ver_index = layer.fields().indexFromName("Column Name")
                if ver_index != -1:
                    feat.setAttribute(ver_index, "SAG Value")
                layer.updateFeature(feat)
                
        else:
            QgsMessageLog.logMessage("Layer is not editable!")




 
    def Set_sample(self):
        order_type_value = 'order_type'
        type_ref_value = 'type_ref'
        QgsMessageLog.logMessage("Entered Function")
    
        layer = iface.activeLayer()
        if not layer:
            QgsMessageLog.logMessage("No active layer found")
            return
    
        if layer.isEditable():
            QgsMessageLog.logMessage("Layer is editable")
            selected_features = layer.selectedFeatures()
            for feat in selected_features:
                order_type_index = layer.fields().indexFromName("order_type")
                type_ref_index = layer.fields().indexFromName("type_ref")
            
                QgsMessageLog.logMessage(f"Index of 'order_type': {order_type_index}")
                QgsMessageLog.logMessage(f"Index of 'type_ref': {type_ref_index}")
            
                if order_type_index != -1 and type_ref_index != -1:
                    feat.setAttribute(order_type_index, "No Loading")
                    feat.setAttribute(type_ref_index, 3)
                    layer.updateFeature(feat)
                else:
                    if order_type_index == -1:
                        QgsMessageLog.logMessage("'order_type' field not found")
                    if type_ref_index == -1:
                         QgsMessageLog.logMessage("'type_ref' field not found")
                
        else:
            QgsMessageLog.logMessage("Layer is not editable!")


      

    def Set_sample(self):
        order_type_value = 'order_type'
        schedule_value = 'schedule'
        type_ref_value = 'type_ref'
        QgsMessageLog.logMessage("Entered Function")
    
        layer = iface.activeLayer()
        if not layer:
            QgsMessageLog.logMessage("No active layer found")
            return
    
        if layer.isEditable():
            QgsMessageLog.logMessage("Layer is editable")
            selected_features = layer.selectedFeatures()
            for feat in selected_features:
                order_type_index = layer.fields().indexFromName("order_type")
                schedule_index = layer.fields().indexFromName("schedule")
                type_ref_index = layer.fields().indexFromName("type_ref")
            
                QgsMessageLog.logMessage(f"Index of 'order_type': {order_type_index}")
                QgsMessageLog.logMessage(f"Index of 'schedule': {schedule_index}")
                QgsMessageLog.logMessage(f"Index of 'type_ref': {type_ref_index}")
            
                if order_type_index != -1 and schedule_index != -1 and type_ref_index != -1:
                    feat.setAttribute(order_type_index, "No Waiting At Any Time")
                    feat.setAttribute(schedule_index, "DYL001")
                    feat.setAttribute(type_ref_index, 2)
                    layer.updateFeature(feat)
                else:
                    if order_type_index == -1:
                        QgsMessageLog.logMessage("'order_type' field not found")
                    if schedule_index == -1:
                        QgsMessageLog.logMessage("'schedule' field not found")
                    if type_ref_index == -1:
                         QgsMessageLog.logMessage("'type_ref' field not found")
        else:
            QgsMessageLog.logMessage("Layer is not editable!")



    def Set_workunit_353(self):
        treecode_value = '1'
        trim_type_value = '3'
        vegremarks_value = 'Y'

        QgsMessageLog.logMessage("Entered Function")
    
        layer = iface.activeLayer()  # Get the currently active layer
        if layer is None or not layer.isValid():
            QgsMessageLog.logMessage("No valid layer selected or layer is invalid!")
            return

        if not layer.isEditable():
            QgsMessageLog.logMessage("Layer is not editable!")
            return

        QgsMessageLog.logMessage("Layer is editable")

        selected_features = layer.selectedFeatures()  # Get selected features
        for feat in selected_features:
            treecode_index = layer.fields().indexFromName("tree_code")  # Get index of "tree_code" field
            trim_type_index = layer.fields().indexFromName("trim_type")  # Get index of "Trim_Type" field
            vegremarks_index = layer.fields().indexFromName("vegremarks")  # Get index of "vegremarks" field
        
            if treecode_index != -1:
                feat.setAttribute(treecode_index, treecode_value)  # Set "tree_code" attribute value
            if trim_type_index != -1:
                feat.setAttribute(trim_type_index, trim_type_value)  # Set "Trim_Type" attribute value
            if vegremarks_index != -1:
                feat.setAttribute(vegremarks_index, vegremarks_value)  # Set "vegremarks" attribute value
        
            layer.updateFeature(feat)  # Update the feature with the new values


          
    def Set_sample_WITHtextBOX(self):
        layer = iface.activeLayer()
        if layer is not None and layer.isEditable():
            selected_features = layer.selectedFeatures()
            for feat in selected_features:
                ver_index = layer.fields().indexFromName("column name")
                # QgsMessageLog.logMessage(str(ver_index))
                sag_val = self.dockwidget.text_input_1.text()  # Use text() method for QLineEdit
                QgsMessageLog.logMessage(str(sag_val))
                if ver_index != -1:
                    feat.setAttribute(ver_index, (sag_val))
                    layer.updateFeature(feat)
        else:
            QgsMessageLog.logMessage("Layer is not editable!")

    def Set_SAG_0(self):
        layer = iface.activeLayer()
        if layer.isEditable():
            selected_features = layer.selectedFeatures()
            for feat  in selected_features:
                ver_index = layer.fields().indexFromName("SAG")
                if ver_index != -1:
                    feat.setAttribute(ver_index, 0)
                layer.updateFeature(feat)
                
        else:
            QgsMessageLog.logMessage("Layer is not editable!")

    def Set_SAG_1(self):
        layer = iface.activeLayer()
        if layer.isEditable():
            selected_features = layer.selectedFeatures()
            for feat  in selected_features:
                ver_index = layer.fields().indexFromName("SAG")
                if ver_index != -1:
                    feat.setAttribute(ver_index, 1)
                layer.updateFeature(feat)
                
        else:
            QgsMessageLog.logMessage("Layer is not editable!")

    def Set_SAG_2(self):
        layer = iface.activeLayer()
        if layer.isEditable():
            selected_features = layer.selectedFeatures()
            for feat  in selected_features:
                ver_index = layer.fields().indexFromName("SAG")
                if ver_index != -1:
                    feat.setAttribute(ver_index, 2)
                layer.updateFeature(feat)
                
        else:
            QgsMessageLog.logMessage("Layer is not editable!")

    def Set_SAG_3(self):
        layer = iface.activeLayer()
        if layer.isEditable():
            selected_features = layer.selectedFeatures()
            for feat  in selected_features:
                ver_index = layer.fields().indexFromName("SAG")
                if ver_index != -1:
                    feat.setAttribute(ver_index, 3)
                layer.updateFeature(feat)
                
        else:
            QgsMessageLog.logMessage("Layer is not editable!")

    def Set_SAG_4(self):
        layer = iface.activeLayer()
        if layer.isEditable():
            selected_features = layer.selectedFeatures()
            for feat  in selected_features:
                ver_index = layer.fields().indexFromName("SAG")
                if ver_index != -1:
                    feat.setAttribute(ver_index, 4)
                layer.updateFeature(feat)
                
        else:
            QgsMessageLog.logMessage("Layer is not editable!")

    def Set_SAG_5(self):
        layer = iface.activeLayer()
        if layer.isEditable():
            selected_features = layer.selectedFeatures()
            for feat  in selected_features:
                ver_index = layer.fields().indexFromName("SAG")
                if ver_index != -1:
                    feat.setAttribute(ver_index, 5)
                layer.updateFeature(feat)
                
        else:
            QgsMessageLog.logMessage("Layer is not editable!")

    def Set_SAG_6(self):
        layer = iface.activeLayer()
        if layer.isEditable():
            selected_features = layer.selectedFeatures()
            for feat  in selected_features:
                ver_index = layer.fields().indexFromName("SAG")
                if ver_index != -1:
                    feat.setAttribute(ver_index, 6)
                layer.updateFeature(feat)
                
        else:
            QgsMessageLog.logMessage("Layer is not editable!")

    def Set_SAG_7(self):
        layer = iface.activeLayer()
        if layer.isEditable():
            selected_features = layer.selectedFeatures()
            for feat  in selected_features:
                ver_index = layer.fields().indexFromName("SAG")
                if ver_index != -1:
                    feat.setAttribute(ver_index, 7)
                layer.updateFeature(feat)
                
        else:
            QgsMessageLog.logMessage("Layer is not editable!")

    def Set_SAG_8(self):
        layer = iface.activeLayer()
        if layer.isEditable():
            selected_features = layer.selectedFeatures()
            for feat  in selected_features:
                ver_index = layer.fields().indexFromName("SAG")
                if ver_index != -1:
                    feat.setAttribute(ver_index, 8)
                layer.updateFeature(feat)
                
        else:
            QgsMessageLog.logMessage("Layer is not editable!")

    def Set_SAG_9(self):
        layer = iface.activeLayer()
        if layer.isEditable():
            selected_features = layer.selectedFeatures()
            for feat  in selected_features:
                ver_index = layer.fields().indexFromName("SAG")
                if ver_index != -1:
                    feat.setAttribute(ver_index, 9)
                layer.updateFeature(feat)
                
        else:
            QgsMessageLog.logMessage("Layer is not editable!")

    def Set_SAG_10(self):
        layer = iface.activeLayer()
        if layer.isEditable():
            selected_features = layer.selectedFeatures()
            for feat  in selected_features:
                ver_index = layer.fields().indexFromName("SAG")
                if ver_index != -1:
                    feat.setAttribute(ver_index, 10)
                layer.updateFeature(feat)
                
        else:
            QgsMessageLog.logMessage("Layer is not editable!")

    def Set_SAG_NULL(self):
        layer = iface.activeLayer()
        if layer.isEditable():
            selected_features = layer.selectedFeatures()
            for feat  in selected_features:
                ver_index = layer.fields().indexFromName("SAG")
                if ver_index != -1:
                    feat.setAttribute(ver_index, 'N/A')
                layer.updateFeature(feat)
                
        else:
            QgsMessageLog.logMessage("Layer is not editable!")


          
    def Set_SAG_BOX(self):
        layer = iface.activeLayer()
        if layer is not None and layer.isEditable():
            selected_features = layer.selectedFeatures()
            for feat in selected_features:
                ver_index = layer.fields().indexFromName("SAG")
                # QgsMessageLog.logMessage(str(ver_index))
                sag_val = self.dockwidget.text_input_1.text()  # Use text() method for QLineEdit
                QgsMessageLog.logMessage(str(sag_val))
                if ver_index != -1:
                    feat.setAttribute(ver_index, (sag_val))
                    layer.updateFeature(feat)
        else:
            QgsMessageLog.logMessage("Layer is not editable!")



            